name: habits_go_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/apple.png
    - assets/facebook.png
    - assets/google.png
    - assets/splash/walking_broccoli.json
    - assets/gatowa.jpg
    - assets/rodrigo_profile.png
